# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Send GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install -g nwb
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: './nwb.prod.config.js'
          authDomain: ${{ secrets.AUTH_DOMAIN }}
          authClientId: ${{ secrets.AUTH_CLIENT_ID }}
          authAudience: ${{ secrets.AUTH_AUDIENCE }}
      - run: npm run build
      - name: deploy docs
        uses: Cecilapp/GitHub-Pages-deploy@2.0.1
        env:
          EMAIL: vladi03@hotmail.com
          GH_TOKEN: ${{ secrets.USER_TOKEN }}
          BUILD_DIR: dist
          CNAME: retail.netware.us